# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ba3fa688-34f1-4cd7-8472-ac97099506aa";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ba3fa688-34f1-4cd7-8472-ac97099506aa".device = "/dev/disk/by-uuid/ba3fa688-34f1-4cd7-8472-ac97099506aa";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2698-6B0B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fb117270-f8f2-44ea-a997-2a8364ebc1a7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
